server:
  mode: development
  grpc:
   host: 0.0.0.0
   port: 10443
  http:
   host: 0.0.0.0
   port: 10080
  flag:
    grpc:
      enabledLogRequest: true
      enabledLogResponse: true
    tracing:
      enabledGORM: true
      enabledRedis: true
