name: Deploy pre-release

on:
  workflow_call:
    inputs:
      services:
        description: 'service glob to deploy, for example router-service/*/{api,indexer}'
        type: string
        required: true
      version:
        description: 'version to deploy'
        type: string
        required: true

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          fingerprint: ${{ secrets.GPG_PUBLIC }}
      - name: Update tag patches
        env:
          ENV: pre-release
          TAG: ${{ inputs.version }}
        run: |
          set -e
          shopt -s nullglob globstar
          CHARTS=(${{ env.ENV }}/${{ inputs.services }}/**/Chart.yaml)
          for dir in ${CHARTS[@]%/*}; do
            if source_files=($dir/.argocd-source-*.yaml); [ ${#source_files[@]} -gt 0 ]; then
              sed -i -E '/server\.image\.tag/,/value:/s/(value: ).+/\1'"$TAG/" $source_files
            else
              sed -i -E "0,/^\s+tag:/s/(tag: ).+/\\1$TAG/" $dir/values.yaml
            fi
          done
          git commit -S -am "[${ENV%-*}] ${{ github.repository }}: deploy $TAG"$'\n\n'"$(
            echo "Co-authored-by: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>")"
          git push origin HEAD
