name: Deploy pre-release

on:
  workflow_call:
    inputs:
      services:
        description: 'service glob to deploy, for example router-service/*/{api,indexer}'
        type: string
        required: true
      tag:
        description: 'tag to deploy'
        type: string
        required: true
      runs-on:
        description: 'Type of machine to run the job on'
        type: string
        default: ${{ github.event.repository.private && 'self-hosted' || 'ubuntu-latest' }}

jobs:
  deploy:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/kyber-applications
          token: ${{ secrets.GH_PAT }}
      - uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          fingerprint: ${{ secrets.GPG_PUBLIC }}
      - name: Update and push tag patches
        env:
          ENV: pre-release
          TAG: ${{ inputs.tag }}
        run: |
          set -e
          shopt -s nullglob globstar
          CHARTS=(${{ env.ENV }}/${{ inputs.services }}/**/Chart.yaml)
          for dir in ${CHARTS[@]%/*}; do
            if source_files=($dir/.argocd-source-*.yaml); [ ${#source_files[@]} -gt 0 ]; then
              sed -i -E '/server\.image\.tag/,/value:/s/(value: ).+/\1'"$TAG/" $source_files
            else
              sed -i -E "0,/^\s+tag:/s/(tag: ).+/\\1$TAG/" $dir/values.yaml
            fi
          done
          git commit -S -am "[${ENV%-*}] ${{ github.event.repository.name }}: deploy $TAG"$'\n\n'"$(
            echo "Triggered by ${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}")"$'\n\n'"$(
            echo "Co-authored-by: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>")"
          git push origin HEAD
          echo "Deployed $TAG with commit https://github.com/${{ github.repository_owner }}/kyber-applications/commit/$(git rev-parse --short HEAD)" >> "$GITHUB_STEP_SUMMARY"
