name: PR to bump Go module version

# Sample concurrency config:
# concurrency:
#   group: ci-workflow-${{ github.ref }}-${{ github.event_name }}
#   cancel-in-progress: true
# Sample permissions config:
# permissions:
#   issues: write
#   pull-requests: write

on:
  workflow_call:
    inputs:
      repos:
        description: 'json arrays of repos to raise bump PRs to'
        type: string
      runs-on:
        description: 'Type of machine to run the job on'
        type: string
        default: ${{ github.event.repository.private && 'self-hosted' || 'ubuntu-latest' }}

jobs:
  bump:
    runs-on: ${{ inputs.runs-on }}
    strategy:
      matrix:
        repo: ${{ fromJson(inputs.repos) }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/${{ matrix.repo }}
          token: ${{ secrets.GH_PAT }}
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: bump version
        env:
          MOD: github.com/${{ github.repository }}
          VER: ${{ github.ref_name }}
        run: |
          git config --global url."https://${{ secrets.GH_PAT }}:x-oauth-basic@github.com/".insteadOf https://github.com/
          go env -w GOPRIVATE=github.com/${{ github.repository_owner }}
          try=0
          while out=$(go get $MOD@$VER 2>&1); EC=$?; echo "$out"; [ $EC -ne 0 ]; do
            sed -i -E '\%^(require)?\s*'"$(<<<"$out" grep -oP 'go: \K[^@]+')"'\s+\S+$%d' go.mod
            [ $((++try)) -gt 3 ] && exit 1
          done
          go mod tidy
      - uses: crazy-max/ghaction-import-gpg@cb9bde2e2525e640591a934b1fd28eef1dcaf5e5 # v6.2.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          fingerprint: ${{ secrets.GPG_PUBLIC }}
      - id: pr
        uses: peter-evans/create-pull-request@67ccf781d68cd99b580ae25a5c18a1cc84ffff1f # v7.0.6
        with:
          token: ${{ secrets.GH_PAT }}
          commit-message: 'chore: bump ${{ github.event.repository.name }} to ${{ github.ref_name }}'
          committer: kyber-ci-bot <kyber-ci-bot@users.noreply.github.com>
          branch: ft/bump_${{ github.event.repository.name }}
          delete-branch: true
          title: 'chore: bump ${{ github.event.repository.name }} to ${{ github.ref_name }}'
          body: |
            * chore: bump ${{ github.event.repository.name }} to ${{ github.ref_name }}

            *PR triggered by [pr-bump-go-mod.yaml](https://github.com/KyberNetwork/service-framework/blob/main/.github/workflows/pr-bump-go-mod.yaml) at ${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}*
      - name: Write summary
        run: |
          echo 'Raised PR at https://github.com/${{ github.repository_owner }}/${{ matrix.repo }}/pull/${{ steps.pr.outputs.pull-request-branch }}' >> "$GITHUB_STEP_SUMMARY"
